// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb_OcE5eLfKWnANNEqIxKdQmey21xTEO0',
    appId: '1:702545317184:web:5ba3dabdff5f12130fbea5',
    messagingSenderId: '702545317184',
    projectId: 'pillpal-6562b',
    authDomain: 'pillpal-6562b.firebaseapp.com',
    storageBucket: 'pillpal-6562b.firebasestorage.app',
    measurementId: 'G-MB04RS6E2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzL89ydd6J6cBKBhRuhFFeV6q5iGrsS0E',
    appId: '1:702545317184:android:8fc69c388ee593350fbea5',
    messagingSenderId: '702545317184',
    projectId: 'pillpal-6562b',
    storageBucket: 'pillpal-6562b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0kglOohvXt3Vt0nIfnnLo0XFJJftHCw',
    appId: '1:702545317184:ios:b6fbb6486d790a1e0fbea5',
    messagingSenderId: '702545317184',
    projectId: 'pillpal-6562b',
    storageBucket: 'pillpal-6562b.firebasestorage.app',
    iosBundleId: 'com.example.mmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0kglOohvXt3Vt0nIfnnLo0XFJJftHCw',
    appId: '1:702545317184:ios:b6fbb6486d790a1e0fbea5',
    messagingSenderId: '702545317184',
    projectId: 'pillpal-6562b',
    storageBucket: 'pillpal-6562b.firebasestorage.app',
    iosBundleId: 'com.example.mmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb_OcE5eLfKWnANNEqIxKdQmey21xTEO0',
    appId: '1:702545317184:web:22fdaeddfa3c1bd30fbea5',
    messagingSenderId: '702545317184',
    projectId: 'pillpal-6562b',
    authDomain: 'pillpal-6562b.firebaseapp.com',
    storageBucket: 'pillpal-6562b.firebasestorage.app',
    measurementId: 'G-LRSVDPH394',
  );
}
